const express = require("express")
const userRouter=express.Router()
const {getUser,updateUser,userProfileUpdate,logoutUSer,deleteUser} = require("../controllers/user")
const {signup,login} = require("../controllers/authcontroller")
const {authorization}=require("../middleware/authorization")
const upload = require("../middleware/upload")
userRouter.post("/adduser",signup)
userRouter.post("/login",login)
userRouter.get("/getuser",authorization,getUser)
userRouter.post("/logout",authorization,logoutUSer)
userRouter.post("/updateuser",authorization,updateUser)
userRouter.post("/updateuserProfile",authorization,upload.single("resume"),userProfileUpdate)
userRouter.delete("/deleteuser",authorization,deleteUser)
module.exports=userRouter